### ISSUE TITLE
楼中楼只能爬取1页

### ISSUE THREAD

**Issue by mp4spig** [hjhee/tiebaSpider#1]
只看了33楼，反复测试几次都是如此
https://tieba.baidu.com/p/5381698176
发现都是这样。
https://tieba.baidu.com/p/3922635509 也是。
3楼爬取的内容，本应是“今晚在重新更吧竟然被删帖了”，结果有三个3楼，中间的一个是正确的，剩余的两个是大量的“希望各位吧友能支持魔吧月刊。”，大概是别的楼层的吧。

**Comment by hjhee** [comment]
用程序[tiebaSpider.zip](https://github.com/hjhee/tiebaSpider/files/1638177/tiebaSpider.zip)替换原版本可以正确获取[https://tieba.baidu.com/p/5381698176](https://tieba.baidu.com/p/5381698176)。除此自外还减少了fetcher线程的数量，这样爬取得时候时间会变慢，但是比较不容易被百度封杀（即一段时间内无法访问百度贴吧）。

出问题的原因：获取的HTML和JSON代码我没有仔细地分析哪些需要html.Unmarshal，哪些不需要，所以之前一股脑全部unescape了一遍，未来应该重新排查一遍URL，分析哪个位置才需要html.Unmarschal。

“希望各位吧友能支持魔吧月刊”这个问题应该是贴吧嵌入的一类广告，能跟帖子混在一起。目前在想办法排除，一个思路是只获取`<div class="l_post l_post_bright j_l_post clearfix">`，因为这种广告的class上除了上面四个之外还包含一个随机数（如`r0dcaebbde`或者`p7ce8fae02`等）。但是因为不熟悉jQuery的选择器语法，所以目前不知道怎么样选择只包含某几个特定数目的class，可能还需要加上程序逻辑判断吧。

但是这个广告不太影响阅读，等下个月有时间了再解决。

**Comment by mp4spig** [comment]
这个[tiebaSpider.zip](https://github.com/hjhee/tiebaSpider/files/1638177/tiebaSpider.zip)不是和v0.1.1版本的一样么。
@hjhee

**Comment by hjhee** [comment]
这个版本能获取所有页的楼中楼，另外在程序获取的过程中也不会出现网页代码解析错误的提示。
除了不能排除广告之外应该是能够正常工作的，把压缩包里面的程序替换原程序就能用。

**Comment by mp4spig** [comment]
并不能啊，解压后的tiebaSpider.exe：
文件名称：C:\Users\mp4sp\Downloads\tiebaSpider.v0.1.1.win64\tiebaSpider.exe
文件大小：8619520 字节
修改时间：2018年1月17日 16:30:00
MD5     ：9CD5855B1B66D7A6745AC487AF4D7B6C
SHA1    ：181F811F00255A433DF945D9A50EDB873FB75949
CRC32   ：CF68C819

33楼还是没获得所有的楼中楼。要不把你获取的结果发我一份？
@hjhee

**Comment by hjhee** [comment]
我没读清楚问题，楼中楼目前确实只能获取一页，用的是[python爬取贴吧楼中楼](https://mrxin.github.io/2015/09/19/tieba-louzhonglou/)提供的方法实现的。

想获取更多页数的话需要先解决楼中楼URL地址怎么构建，可以试试用Wireshark抓包试试。成功之后另一个问题是需要判断楼中楼总页数并按需要获取。

只能等2月份再解决了。

**Comment by mp4spig** [comment]
嘿嘿，先期待了(●ˇ∀ˇ●)
@hjhee

**Comment by hjhee** [comment]
9c82d4e381d1bcd3f801bf5f6c07960fb7d829be 尝试修复了广告问题，利用自定义逻辑去除所有class数量大于4的元素

**Comment by mp4spig** [comment]
大神考虑更新下吧😂

**Comment by hjhee** [comment]
有什么问题吗？你那个帖子应该能正确下载了吧？只是其他楼中楼的日期格式不一致而已
[new Version](https://github.com/hjhee/tiebaSpider/releases/tag/v0.1.3)
