### ISSUE TITLE
同样运行不了,望更新解决

### ISSUE THREAD

**Issue by CberYellowstone** [hjhee/tiebaSpider#10]
这是当时的日志
`[root@localhost tiebaSpider]# go run main.go 

`#` command-line-arguments

./main.go:72:19: undefined: fetchHTMLList

./main.go:73:22: undefined: parseHTML

./main.go:74:25: undefined: renderHTML

./main.go:87:16: select case must be receive, send or assign recv

./main.go:94:16: select case must be receive, send or assign recv

./main.go:101:16: select case must be receive, send or assign recv

./main.go:108:17: select case must be receive, send or assign recv
`

**Comment by hjhee** [comment]
整个程序的代码分布在多个文件里，若用`go run`命令运行`main.go`的话，某些结构体和函数编译器没办法找到而报错。

若不需要自己修改代码，可以在release页面找到现成的二进制文件；否则得看看go语言教程补充基础，例如：[How to compile Go program consisting of multiple files?](https://stackoverflow.com/a/55700707)
