### ISSUE TITLE
不知道这是个什么BUG

### ISSUE THREAD

**Issue by LoneFireBlossom** [hjhee/tiebaSpider#12]
我在.txt里记录了这四个链接，结果就打开tiebaspider之后就出现下面这样的error提示；不过文件倒是都生成了。（我不知道生成的有没有错误）
于是我把output文件夹清空了，这几个链接一个一个粘贴保存爬取，这次就没发现有下图这样的error提示。不知道什么情况，总之来这儿记录一下。
https://tieba.baidu.com/p/6686629174
https://tieba.baidu.com/p/6687216651
https://tieba.baidu.com/p/6687241276
https://tieba.baidu.com/p/6687266097
   
![image](https://user-images.githubusercontent.com/50087596/82732471-fceb4900-9d3f-11ea-982c-c53dde649f9d.png)

**Comment by LoneFireBlossom** [comment]
好像还是有这个BUG
考完研终于可以继续鼓捣了……
![image](https://user-images.githubusercontent.com/50087596/104153866-69759e00-541e-11eb-8229-6ea30975ac81.png)

**Comment by LoneFireBlossom** [comment]
下面这个帖子在保存时也有上述问题
https://tieba.baidu.com/p/7201761174
之前虽然有上述问题不过我没发现保存下来有啥毛病，这次这个帖子我就发现了，2楼的楼中楼回复没了，以及下面一长串重复的内容

**Comment by hjhee** [comment]
你说的问题我都改了，试试[这里](https://github.com/hjhee/tiebaSpider/actions/runs/712204146)编译好的artifacts，若没问题就可以再发布一个新的版本

**Comment by LoneFireBlossom** [comment]
十分感谢继续维护！
我试了试楼上的帖子 https://tieba.baidu.com/p/7201761174
还是有问题呀，我用chrome打开获得的文件，2楼-9楼的楼中楼全都没有获取到，后面比如12楼等地方的楼中楼也没有获取到。示意图如下：

![image](https://user-images.githubusercontent.com/50087596/113466328-8645ce80-946d-11eb-88a8-d16dcd03c9c9.png)

**Comment by hjhee** [comment]
不清楚你用的是什么版本的程序，在我电脑里面是能获取到结果的，下面的压缩包里面，用firefox浏览器打开能看见有所有的楼中楼

[example.zip](https://github.com/hjhee/tiebaSpider/files/6251911/example.zip)

**Comment by LoneFireBlossom** [comment]
啊 我以为你的系统下面也会有这样的问题所以就没补充，是这样的，
我打开代码运行发现

额，又不对了，我现在发现，这个BUG好像是随机出现的。有的时候运行tiebaspider.exe，output文件夹中的结果是有这些楼中楼的；而有的时候则没有。
比如，没有楼中楼的output，我用记事本打开是这样的：
![image](https://user-images.githubusercontent.com/50087596/113470423-1a249400-9488-11eb-9fe4-08cd30702ccd.png)
运行完的程序压缩包为：
[win64.zip](https://github.com/hjhee/tiebaSpider/files/6252051/win64.zip)

有楼中楼的output，我用记事本打开是这样的（无论是否先把之前的输出删掉，也即无论是否覆盖之前的输出，都会这样）：
![image](https://user-images.githubusercontent.com/50087596/113470430-332d4500-9488-11eb-8383-44bc25a9a909.png)
运行完的程序压缩包为：
[win64.zip](https://github.com/hjhee/tiebaSpider/files/6252053/win64.zip)

---

因为我不是程序员（希望考上研能抓紧时间学会编程……）所以不知道有哪些方面会影响程序的运行。

我看到运行tiebaspider.exe的时候，下面这个命令行窗口中，每次显示的语句啊数字啊都有所不同的样子（这里我可能没有把所有语句都截取到，因为窗口在结束运行后会自动消失）。
![image](https://user-images.githubusercontent.com/50087596/113470368-9c608880-9487-11eb-96b0-084fccd49b00.png)

![image](https://user-images.githubusercontent.com/50087596/113470558-0b8aac80-9489-11eb-913c-251483a9bbd9.png)

**Comment by LoneFireBlossom** [comment]
另外，我的电脑系统是win10最新版。
在1月我报这个帖子中的BUG的时候，当时我用的是另一台电脑；
现在我换了一台新电脑，运行的这个程序。

程序存放的路径是D:\apps\win64。

**Comment by hjhee** [comment]
倒数第二张命令行窗口截图很有用，这说明程序本身在未获取所有评论和楼中楼的情况下就输出了结果。现在重新检查了一遍任务添加、删除、查询的代码，并加入了获取错误自动重试的功能。这种情况应该不会再出现了。

https://github.com/hjhee/tiebaSpider/actions/runs/714772921

**Comment by LoneFireBlossom** [comment]
嗯，这次试了几次都没有问题。
十分感谢！
