### ISSUE TITLE
楼中楼用户名称错误

### ISSUE THREAD

**Issue by Gong-air** [hjhee/tiebaSpider#19]
您好，首先感谢您开源的代码
由于我比较关注的是楼中楼内的回复关系，但是爬取出的楼中楼内名称是错误的，如下：
![image](https://user-images.githubusercontent.com/77915156/233441938-c4f370ed-638c-4653-93cf-3cfbd81d230e.png)
![image](https://user-images.githubusercontent.com/77915156/233442011-f153d9fd-4676-4c34-8795-c90568ef2047.png)
这种情况应该怎么办呢？感谢！

**Comment by hjhee** [comment]
增加了配置 `showUserNickname`，切换原名称和昵称.

不太清楚昵称每次变动的时候, 以前的结果是否会得到更新.
