### ISSUE TITLE
可以支持WAP版爬取吗？

### ISSUE THREAD

**Issue by mp4spig** [hjhee/tiebaSpider#2]
最近贴吧隐藏2017年之前的帖子，只有WAP版可见。
http://tieba.baidu.com/mo/m?kz=[帖子id]

**Comment by hjhee** [comment]
实现起来不麻烦，不过最近几个月没时间修改代码

**Comment by hjhee** [comment]
[这个版本](https://github.com/hjhee/tiebaSpider/actions/runs/715317257)现在支持WAP获取了，可以测试一下
