### ISSUE TITLE
贴吧id显示错误

### ISSUE THREAD

**Issue by LoneFireBlossom** [hjhee/tiebaSpider#4]
首先还是感谢您能发布这么好的东西。试了几个帖子。

1、如果贴吧id后面有带表情符号的话，会乱码。例如这个帖子，
https://tieba.baidu.com/p/6209031748?pn=3
77楼的ID是“你失散的野爹😂”，用这个软件保存的结果是“钃濋瓟铦庰煢”

2、在楼中楼里的“A回复B：……”中，B有链接。但是打开这个链接会显示错误。
感觉不如直接把这个链接删了。

**Comment by hjhee** [comment]
问题1已经通过解析HTML代码的方式获取用户名解决。若用户名中带有表情符号或图片，目前还没办法正常显示，这个问题计划在 #5 的基础上想办法。要是有简单的思路的话就好了。
