### ISSUE TITLE
建议：将缩略图图片链接替换为原图

### ISSUE THREAD

**Issue by LoneFireBlossom** [hjhee/tiebaSpider#5]
现在，这个工具爬取到的图片链接都是缩略图链接。爬取得到的网页，打开之后显示的自然也是缩略图链接。
而且还无法自动查看大图，原帖子里点击缩略图是可以查看大图的。

我想，反正用这个工具的人都是用电脑和宽带，没人会在乎流量吧。所以不如直接把图片链接替换成原图。
我找了几个帖子里面的图片，发现图片链接的命名挺好改的：
缩略图链接（这些链接似乎要手动复制粘贴到输入网址的地方才能打开，当然，在爬取得到的html文件里都是能正常显示的）：
https://imgsa.baidu.com/forum/w%3D580/sign=b13fff0d831001e94e3c1407880c7b06/917edd628535e5ddf5e2133b78c6a7efcc1b6240.jpg
https://imgsa.baidu.com/forum/w%3D580/sign=93928a239e529822053339cbe7cb7b3b/b5dc04338744ebf8cffdd2dbd7f9d72a6259a787.jpg
https://imgsa.baidu.com/forum/w%3D580/sign=ffabff668e0a19d8cb03840d03fb82c9/aa482ec79f3df8dce2142946c311728b46102847.jpg
https://imgsa.baidu.com/forum/w%3D580/sign=f74848d9e724b899de3c79305e071d59/7a6b1dfa513d2697869e6a845bfbb2fb4216d826.jpg
大图链接：
https://imgsrc.baidu.com/forum/pic/item/917edd628535e5ddf5e2133b78c6a7efcc1b6240.jpg
https://imgsrc.baidu.com/forum/pic/item/b5dc04338744ebf8cffdd2dbd7f9d72a6259a787.jpg
https://imgsrc.baidu.com/forum/pic/item/aa482ec79f3df8dce2142946c311728b46102847.jpg
http://imgsrc.baidu.com/forum/pic/item/7a6b1dfa513d2697869e6a845bfbb2fb4216d826.jpg
我不懂程序，感觉只要在爬取完毕后进行全部替换：
https://imgsa.baidu.com/forum/.{1,45}
http://imgsrc.baidu.com/forum/pic/item
就能实现这个功能。

贴吧的表情的链接是这样的，不会被上面的替换影响到，所以应该不会有问题。
https://gsp0.baidu.com/5aAHeD3nKhI2p27j8IqW0jdnxx1xbK/tb/editor/images/client/image_emoticon13.png

当然这个也可以我自己手动做，下载下来之后用文本编辑器打开html全部替换就行了。
我是因为贴吧把以前的贴隐藏了才认识到必须得把重要帖子保存起来，然后搜了一圈就只发现了您这个最合适，能爬取一个帖子的所有内容（含所有楼中楼、图片），而且还能以html的形式保存下来！
所以对我来说，真正影响使用的是前面说的无法获得帖子最后一页的楼中楼，如果您看到这issue能不能说一下关于这点改起来是麻烦还是简单呢，如果不算麻烦的话希望能修改，现在我是日日盼夜夜盼😂
我不懂编程，所以如果掏钱能让您愿意把这点改进的话也好啊，我愿意赞助一些（50您看行不= =），谢谢了🙏

**Comment by hjhee** [comment]
缺失最后一页楼中楼的问题已经解决了，你可以再测试一下。至于修改图片链接的问题，个人认为是把图片下载到本地才是正解，这里涉及图片下载和URL链接改写的问题，代码修改起来不像 #3 一样简单。我目前精力有限，所以只能处理一些简单的问题。

**Comment by LoneFireBlossom** [comment]
试了试发现可以了，谢谢！

> 个人认为是把图片下载到本地才是正解

我是打算用印象笔记保存帖子的。所以我的思路是这样的：
1、用tiebaspider将帖子保存为html文件；
2、打开html文件，将所有缩略图链接替换成原图链接并保存；
3、用chrome打开html文件，然后再用chrome将本页面保存，此时所有原图都会被下载到本地了；
4、把.html文件直接拖动到印象笔记里，就能生成一条格式基本一样的笔记。如图，除了楼中楼应该有一个框给框起来却没了以外，其余都很好，我觉得非常适合保存：
![image](https://user-images.githubusercontent.com/50087596/63066684-e789f880-bf3d-11e9-9db5-713a53cf8108.png)

之所以要用chrome再次保存一下是因为如果直接把tiebaspider下载的html文件拖进去，会无法获得图片：
![image](https://user-images.githubusercontent.com/50087596/63066747-32a40b80-bf3e-11e9-81ed-97ae7d7d81cb.png)
如果打开网页直接复制粘贴的话，图片也是如此。（不过这样能保存楼中楼的框）
综上我必须选择第一种方法。

因为有这种方法存在所以我觉得tiebaspider这个工具是否把图片下载到本地倒无所谓了，哈哈

**Comment by XDcedar** [comment]
改写URL链接的话 已经有[现成的javascript代码](https://greasyfork.org/scripts/2312)了, 改改大概就能用吧
```
if( !(m = url.match(/^https?:\/\/imgsrc\.baidu\.com\/forum\/pic\/item\/.+/i)) ){
	if( (m = url.match(/^(https?):\/\/(?:imgsrc|imgsa|\w+\.hiphotos)\.(?:bdimg|baidu)\.com\/(?:forum|album)\/.+\/(\w+\.(?:jpg|jpeg|gif|png|bmp|webp))(?:\?.+)?$/i)) ){
		document.location = m[1] + "://imgsrc.baidu.com/forum/pic/item/" + m[2];
	}
```

顺便说下..不建议筛选掉无意义回复..无意义回复其实也有存在意义, 而且这个工作应该交给其他工具来做..况且无意义回复本身占空间也不大, 留着也没关系..

**Comment by LoneFireBlossom** [comment]
同意楼上关于无意义回复的说法

**Comment by hjhee** [comment]
我担心直接替换链接地址会导致大文件打开的时候，图片加载速度下降或者带宽不够导致下载失败，甚至内存不足导致浏览器崩溃。原图片下载到本地的功能我会在下个月考虑实现，估计需要解决查询本地目录文件是否存在、图片是否已加载进下载队列等问题。

**Comment by LoneFireBlossom** [comment]
这个倒是，我用我上面说的这种方法（替换为大图→打开.html→用chrome再保存一遍）保存的时候都是在打开.html这一步先从头到尾滚动一遍页面。如果打开.html文件后立刻就保存，有些图就保存不下来。

**Comment by LoneFireBlossom** [comment]
好像就是最近一段时间贴吧换了小图链接了，导致这个方法失效了……我对正则表达式不熟，又要重新研究怎么替换= =

现在是这样的，在爬取的html文件里的图片格式是这样的，是小图：
http://tiebapic.baidu.com/forum/w%3D580/sign=fa9bff75584a20a4311e3ccfa0539847/2ca3b6096b63f624d2ed9e649044ebf81b4ca366.jpg
如果右键打开这个图片，那没几秒种它会自动跳转到下面的链接，变成大图：
http://tiebapic.baidu.com/forum/pic/item/2ca3b6096b63f624d2ed9e649044ebf81b4ca366.jpg


http://tiebapic.baidu.com/forum/.{1,45}
http://tiebapic.baidu.com/forum/pic/item

感觉现在不会编程寸步难行啊……我是不是得考个计算机的研究生……

**Comment by hjhee** [comment]
我给 [v0.1.4](../releases/tag/v0.1.4) 增加了浏览器端代码，用javascript可以替换高清图为原图。方法是修改`config.toml`指定的模板，查看内部给的注释。用这种办法，需要增加代码处理图片加载失效并自动重试的功能。有这方面经验的人或愿意学习的同学可以研究下`template2.html`的底部代码。

直接把图片嵌入html的思路也能做，需要给`fetcher`增加获取图片的代码、检测图片是否已经获取到本地；`parser`需要查询筛选指定链接的图片，然后提交图片获取任务，等待获取完毕之后，通过hash代码替换图片的URL为相应的[`css background`](https://stackoverflow.com/a/7176185)。最后`render`需要在html模板上面植入base64编码的图片。

不过时间精力受限，近期是不会再动程序了……

**Comment by LoneFireBlossom** [comment]
十分感谢，等我先从基本的开始学起，一点一点来😂
老师面试的时候问我你是愿意偏算法还是偏实现，我说我愿意搞能实际落地的😂

**Comment by hjhee** [comment]
那祝你研究生学业顺利了，个人体会兴趣是最好的老师真不假。你要愿意可以看看前端的方法，javascript容易上手。这里有个教材我也在抽空看看，关于现代、地道的javascript编程：[The Modern JavaScript Tutorial](https://javascript.info/)

**Comment by LoneFireBlossom** [comment]
好的，多谢😂不过还是得先看看老师给我布置啥任务……先把老师要求的掌握个起码基础再搞自己的

---
现在被要求先搞Python😂

**Comment by hjhee** [comment]
f34cd75 终于实现了这个功能, 快拖了一年了😃.
