### ISSUE TITLE
这个帖子爬不到

### ISSUE THREAD

**Issue by LoneFireBlossom** [hjhee/tiebaSpider#6]
https://tieba.baidu.com/p/6190643216

试了好几次，把这个url保存到txt里爬不到任何东西，其它帖子url放在txt里就没问题

以后要是有使用问题的话我是再开一个issue还是在这个帖子里回复呀😂

**Comment by LoneFireBlossom** [comment]
又发现一个
https://tieba.baidu.com/p/6244555866

![image](https://user-images.githubusercontent.com/50087596/64465475-6a6a3180-d13f-11e9-95ca-3874c20ca2ea.png)

**Comment by LoneFireBlossom** [comment]
https://tieba.baidu.com/p/4801477065
![image](https://user-images.githubusercontent.com/50087596/64467970-23853780-d151-11e9-82dd-4b17b3db8f27.png)

**Comment by hjhee** [comment]
看错误记录，应该是文件名无法在操作系统创建导致的问题，代码作些许改动就好

每个问题都应该单独开一个issue方便记录
