### ISSUE TITLE
帖子标题包含不能作为文件名的符号时无法生成文件

### ISSUE THREAD

**Issue by brookchou** [hjhee/tiebaSpider#7]
当帖子标题里包含“:”、“|”这种不能作为文件名的符号的时候抓取网页将不会生成html和json文件。请问能否设置在遇到这种情形的时候在文件名里舍去这类符号，或者替换成符合要求的符号呢？

**Comment by hjhee** [comment]
#6 讨论了同样的问题，最新的编译版本 3878d6d 已经把它修复好了。如果抓取还有问题可以在这里留言给出一些例子。
