### ISSUE TITLE
运行不了是怎么回事

### ISSUE THREAD

**Issue by hanslight** [hjhee/tiebaSpider#9]
go run main.go
输出如下
.\main.go:72:19: undefined: fetchHTMLList
.\main.go:73:22: undefined: parseHTML
.\main.go:74:25: undefined: renderHTML
.\main.go:87:16: select case must be receive, send or assign recv
.\main.go:94:16: select case must be receive, send or assign recv
.\main.go:101:16: select case must be receive, send or assign recv
.\main.go:108:17: select case must be receive, send or assign recv

**Comment by hjhee** [comment]
#10 反映了相同的问题，我在那个地方回复了。
